POST http://localhost:8000/enemies HTTP/1.1
content-type: application/json

{
    "id": 0,
    "name": "Animated Armor",
    "level": 2,
    "traits": [
        "common",
        "med",
        "construct",
        "mindless"
    ],
    "perception": 6,
    "skills": {
        "athletics": 9
    },
    "attributeModifiers": {
        "str": 3,
        "dex": -3,
        "con": 4,
        "int": -5,
        "wis": 0,
        "cha": -5
    },
    "defenses": {
        "armorClass": 17,
        "saves": {
            "fortitude": 10,
            "reflex": 3,
            "will": 4
        }
    },
    "maxHitPoints": 20,
    "immunities": [
        "vitality",
        "void"
    ],
    "speed": 20,
    "actions": {
        "attacks": {
            "Longsword": {
                "attackBonus": 11,
                "damage": "1d8+4",
                "damageType": "slashing"
            },
            "Armored Fist": {
                "attackBonus": 9,
                "damage": "1d6+4",
                "damageType": "bludgeoning"
            }
        }
    }
}

###

GET http://localhost:8000/enemies HTTP/1.1

###