[project]
name = "trailmarker"
version = "0.1.0"
description = ""
authors = [
    {name = "Robin Phillips",email = "robinphillips462@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlalchemy (>=2.0.44,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
