import_fighter_data = {
    "name": "Valeros",
    "level": 1,
    "perception": 5,
    "skills": {
        "acrobatics": 5,
        "arcana": 1,
        "athletics": 7,
        "crafting": 4,
        "deception": 0,
        "diplomacy": 3,
        "intimidation": 3,
        "lore": 4,
        "medicine": 0,
        "nature": 0,
        "occultism": 1,
        "performance": 0,
        "religion": 0,
        "society": 1,
        "stealth": 2,
        "survival": 3,
        "thievery": 2,
    },
    "attribute_modifiers": {
        "strength": 4,
        "constitution": 2,
        "dexterity": 2,
        "intelligence": 1,
        "wisdom": 0,
        "charisma": 0,
    },
    "defenses": {
        "armor_class": 18,
        "saves": {"fortitude": 7, "reflex": 7, "will": 3},
    },
    "max_hit_points": 24,
    "spell_attack_bonus": 0,
    "spell_dc": 0,
    "speed": 25,
    "actions": {
        "attacks": [
            {
                "name": "Longsword",
                "attackBonus": 9,
                "damage": "1d8+4",
                "damageType": "slashing",
                "range": None,
                "traits": ["versatile-p"],
            },
            {
                "name": "Dagger",
                "attackBonus": 9,
                "damage": "1d4+4",
                "damageType": "piercing",
                "range": None,
                "traits": ["agile", "finesse", "thrown-10", "versatile-s"],
            },
            {
                "name": "Shortbow",
                "attackBonus": 7,
                "damage": "1d6",
                "damageType": "piercing",
                "range": 60,
                "traits": ["deadly-d10"],
            },
        ],
        "spells": [],
        "heals": 0,
        "shield": 2,
        "sneak_attack": False,
    },
    "user_id": 1,
    "player": "",
    "xp": 0,
    "ancestry": "Human",
    "heritage": "Warden",
    "background": "Farmhand",
    "class": "Fighter",
}

import_cleric_data = {
    "name": "Kyra",
    "level": 1,
    "perception": 7,
    "skills": {
        "acrobatics": 1,
        "arcana": 0,
        "athletics": 1,
        "crafting": 0,
        "deception": 2,
        "diplomacy": 5,
        "intimidation": 2,
        "lore": 3,
        "medicine": 7,
        "nature": 4,
        "occultism": 0,
        "performance": 2,
        "religion": 7,
        "society": 0,
        "stealth": 1,
        "survival": 7,
        "thievery": 1,
    },
    "attribute_modifiers": {
        "strength": 1,
        "constitution": 1,
        "dexterity": 1,
        "intelligence": 0,
        "wisdom": 4,
        "charisma": 2,
    },
    "defenses": {
        "armor_class": 16,
        "saves": {"fortitude": 6, "reflex": 4, "will": 9},
    },
    "max_hit_points": 21,
    "spell_attack_bonus": 7,
    "spell_dc": 17,
    "speed": 25,
    "actions": {
        "attacks": [
            {
                "name": "Scimitar",
                "attackBonus": 4,
                "damage": "1d6+1",
                "damageType": "slashing",
                "range": None,
                "traits": ["forceful", "sweep"],
            }
        ],
        "spells": [
            {
                "name": "Vitality Lash",
                "slots": 1,
                "level": 0,
                "damage_roll": "2d6",
                "damage_type": "vitality",
                "range": 30,
                "area": {},
                "save": "fortitude",
                "targets": 1,
                "actions": "2",
            },
            {
                "name": "Breathe Fire",
                "slots": 1,
                "level": 1,
                "damage_roll": "2d6",
                "damage_type": "fire",
                "range": 5,
                "area": {"type": "cone", "value": "15"},
                "save": "reflex",
                "targets": 0,
                "actions": "2",
            },
        ],
        "heals": 5,
        "shield": 2,
        "sneak_attack": False,
    },
    "user_id": 1,
    "player": "",
    "xp": 0,
    "ancestry": "Human",
    "heritage": "Warden",
    "background": "Acolyte",
    "class": "Cleric",
}


import_rogue_data = {
    "name": "Merisiel",
    "level": 1,
    "perception": 7,
    "skills": {
        "acrobatics": 7,
        "arcana": 1,
        "athletics": 4,
        "crafting": 4,
        "deception": 3,
        "diplomacy": 3,
        "intimidation": 3,
        "lore": 4,
        "medicine": 5,
        "nature": 2,
        "occultism": 1,
        "performance": 0,
        "religion": 2,
        "society": 4,
        "stealth": 7,
        "survival": 5,
        "thievery": 7,
    },
    "attribute_modifiers": {
        "strength": 1,
        "constitution": 1,
        "dexterity": 4,
        "intelligence": 1,
        "wisdom": 2,
        "charisma": 0,
    },
    "defenses": {
        "armor_class": 18,
        "saves": {"fortitude": 4, "reflex": 9, "will": 7},
    },
    "max_hit_points": 15,
    "spell_attack_bonus": 0,
    "spell_dc": 0,
    "speed": 30,
    "actions": {
        "attacks": [
            {
                "name": "Rapier",
                "attackBonus": 7,
                "damage": "1d6+4",
                "damageType": "piercing",
                "range": None,
                "traits": ["deadly-d8", "finesse"],
            },
            {
                "name": "Shortsword",
                "attackBonus": 7,
                "damage": "1d6+4",
                "damageType": "piercing",
                "range": None,
                "traits": ["agile", "finesse", "versatile-s"],
            },
            {
                "name": "Dagger",
                "attackBonus": 7,
                "damage": "1d4+4",
                "damageType": "piercing",
                "range": None,
                "traits": ["agile", "finesse", "thrown-10", "versatile-s"],
            },
        ],
        "spells": [],
        "heals": 0,
        "shield": 0,
        "sneak_attack": False,
    },
    "user_id": 1,
    "player": "",
    "xp": 0,
    "ancestry": "Elf",
    "heritage": "Whisper Elf",
    "background": "Criminal",
    "class": "Rogue",
}


import_wizard_data = {
    "name": "Ezren",
    "level": 1,
    "perception": 4,
    "skills": {
        "acrobatics": 5,
        "arcana": 7,
        "athletics": 0,
        "crafting": 7,
        "deception": 0,
        "diplomacy": 3,
        "intimidation": 0,
        "lore": 7,
        "medicine": 4,
        "nature": 4,
        "occultism": 7,
        "performance": 0,
        "religion": 4,
        "society": 7,
        "stealth": 2,
        "survival": 4,
        "thievery": 5,
    },
    "attribute_modifiers": {
        "strength": 0,
        "constitution": 2,
        "dexterity": 2,
        "intelligence": 4,
        "wisdom": 1,
        "charisma": 0,
    },
    "defenses": {
        "armor_class": 15,
        "saves": {"fortitude": 5, "reflex": 5, "will": 6},
    },
    "max_hit_points": 16,
    "spell_attack_bonus": 7,
    "spell_dc": 17,
    "speed": 25,
    "actions": {
        "attacks": [
            {
                "name": "Dagger",
                "attackBonus": 5,
                "damage": "1d4",
                "damageType": "piercing",
                "range": None,
                "traits": ["agile", "finesse", "thrown-10", "versatile-s"],
            },
            {
                "name": "Staff",
                "attackBonus": 3,
                "damage": "1d8",
                "damageType": "bludgeoning",
                "range": None,
                "traits": [],
            },
            {
                "name": "Crossbow",
                "attackBonus": 5,
                "damage": "1d8",
                "damageType": "piercing",
                "range": 120,
                "traits": [],
            },
        ],
        "spells": [
            {
                "name": "Gouging Claw",
                "slots": 1,
                "level": 0,
                "damage_roll": "2d6",
                "damage_type": "slashing",
                "range": 5,
                "area": {},
                "save": None,
                "targets": 1,
                "actions": "2",
            },
            {
                "name": "Telekinetic Projectile",
                "slots": 1,
                "level": 0,
                "damage_roll": "2d6",
                "damage_type": "bludgeoning",
                "range": 30,
                "area": {},
                "save": None,
                "targets": 1,
                "actions": "2",
            },
            {
                "name": "Force Barrage",
                "slots": 2,
                "level": 1,
                "damage_roll": "1d4+1",
                "damage_type": "force",
                "range": 120,
                "area": {},
                "save": None,
                "targets": 1,
                "actions": "1 to 3",
            },
            {
                "name": "Breathe Fire",
                "slots": 1,
                "level": 1,
                "damage_roll": "2d6",
                "damage_type": "fire",
                "range": 5,
                "area": {"type": "cone", "value": 15},
                "save": "reflex",
                "targets": 0,
                "actions": "2",
            },
        ],
        "heals": 0,
        "shield": 0,
        "sneak_attack": False,
    },
    "user_id": 1,
    "player": "",
    "xp": 0,
    "ancestry": "Human",
    "heritage": "Skilled (BB)",
    "background": "Scholar (Arcana)",
    "class": "Wizard",
}
